import Head from "next/head";
import Home_page from "../src/components/home/home_page";
import styles from "../styles/Home.module.css";

export default function Home({ title, data }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Learn Next Js </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Home_page data={data} title={title} />
        </div>
    );
}

/**
 * this will run first "pre-render"
 * because this is a server side code
 * so it runs the server side code then component and inside it
 */

// getServerSideProps function SSR will prerender before the page
//  and the page can use the data returned by the function
export async function getServerSideProps() {
    // in case we want fetch from a url or an external api
    // const events_categories = await fetch(
    //     "http://localhost:8800/events_categories"
    // ).then((res) => res.json());

    // we can just import it from internal resource
    const { events_categories } = await import("/data/data.json");

    return {
        // props will be passed to the page component as props
        props: {
            title: "Home Page Coming Events",
            data: events_categories,
        },
    };
}
